### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [sanzencode/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by sanzencode** [comment]
I added the HTML meta name="viewport" content="width=device-width"
and then added the css - @-ms-viewport{  width: device-width;}
hopefully that did the trick. It looks good on my phone!

**Comment by kenmazaika** [comment]
Awesome!  The HTML tag:

```
  <meta name="viewport" content="width=device-width">
```

Was exactly what we were looking for! :)  :+1:
